version: 2

unit_tests: &unit_tests
  steps:
    - checkout
    - restore_cache:
        key: dependency-cache-{{ checksum "package-lock.json" }}
    - run:
        name: Run unit tests.
        command: npm run ci:test

jobs:
  dependency_cache:
    docker:
      - image: rollupcabal/circleci-node-base:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
  node-v14-latest:
    docker:
      - image: rollupcabal/circleci-node-v14:latest
    <<: *unit_tests
  node-v16-latest:
    docker:
      - image: rollupcabal/circleci-node-v16:latest
    <<: *unit_tests
  node-v18-latest:
    docker:
      - image: rollupcabal/circleci-node-v18:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Run unit tests.
          command: npm run ci:coverage
      - run:
          name: Submit coverage data to codecov.
          command: bash <(curl -s https://codecov.io/bash)
          when: on_success
  analysis:
    docker:
      - image: rollupcabal/circleci-node-base:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Run linting.
          command: npm run lint
      - run:
          name: Run Security Check
          command: npm run security
workflows:
  version: 2
  validate:
    jobs:
      - dependency_cache
      - node-v18-latest:
          requires:
            - dependency_cache
          filters:
            tags:
              only: /.*/
      - analysis:
          requires:
            - dependency_cache
          filters:
            tags:
              only: /.*/
      - node-v16-latest:
          requires:
            - dependency_cache
          filters:
            tags:
              only: /.*/
      - node-v14-latest:
          requires:
            - dependency_cache
          filters:
            tags:
              only: /.*/
