name: Node

on: [push]

jobs:
  build:

    runs-on: windows-2019

    strategy:
      matrix:
        node: [ '18', '16', '14' ]

    name: ${{ matrix.node }} (Windows)
    steps:
    - name: Configure git line-breaks
      run: git config --global core.autocrlf false
    - name: Checkout Commit
      uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: Install dependencies
      run: npm ci --ignore-scripts
    - name: Run tests
      run: npm test
      env:
        CI: true
